name: Health check

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/is-my-site-up@v1.1
        with:
          site: 'https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com'