name: Health check

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  health_check_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: jtalk/url-health-check-action@v1.2
        with:
          url: 'https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com'