name: Health check

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Ping
        uses: actions/is-my-site-up@v1.1
        site: `https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com`