name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-16.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
    steps:
      - name: Now it is
        run: "date"
    steps:
      - name: Directory content
        run: "ls -l"